/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INodeStakingOriginal,
  INodeStakingOriginalInterface,
} from "../INodeStakingOriginal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_validatorCandidate",
        type: "address",
      },
    ],
    name: "getValidatorCandidateStakingStatus",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "enum INodeStakingOriginal.StakingStage",
        name: "",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_validatorCandidate",
        type: "address",
      },
    ],
    name: "isValidatorCandidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INodeStakingOriginal__factory {
  static readonly abi = _abi;
  static createInterface(): INodeStakingOriginalInterface {
    return new utils.Interface(_abi) as INodeStakingOriginalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INodeStakingOriginal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as INodeStakingOriginal;
  }
}
